In [1]:
import pandas as pd
import numpy as np

In [33]:
df = pd.read_csv('stats.csv')
df.head(n=10)
#split the last_name,first_name column to be two sepearate columns 1 for first name, 1 for last name by first creating a full_name column then splitting
df[['full_name']]= df[['last_name, first_name']]
df[['last_name','first_name']]=df.full_name.str.split(', ',expand=True)

#drop the original last_name,first_name columns 
df.drop('last_name, first_name',axis = 1,inplace=True)

print(f'There are {len(df)} observations made on {len(df.columns)} features considered in this dataset. ' +
      f' \n ' +
      f'Those features are: ' +
      f' \n')
    
for column in df.columns:
    print(column)

print(f'\n Feature of interest: on_base_plus_slg')

There are 538 observations made on 25 features considered in this dataset.
 Those features are:

player_id
year
pa
hit
single
double
triple
home_run
k_percent
bb_percent
on_base_plus_slg
exit_velocity_avg
sweet_spot_percent
barrel_batted_rate
solidcontact_percent
hard_hit_percent
avg_best_speed
avg_hyper_speed
whiff_percent
swing_percent
groundballs_percent
flyballs_percent
full_name
last_name
first_name

 Feature of interest: on_base_plus_slg

In [34]:
print(f'\n Checking for missing (Na) values: \n ')
print(f'{df.isna().sum()}')
print(f'\n Checking for duplicated values: \n ')
print(f'{df.duplicated().sum()}')

 Checking for missing (Na) values:

player_id               0
year                    0
pa                      0
hit                     0
single                  0
double                  0
triple                  0
home_run                0
k_percent               0
bb_percent              0
on_base_plus_slg        0
exit_velocity_avg       0
sweet_spot_percent      0
barrel_batted_rate      0
solidcontact_percent    0
hard_hit_percent        0
avg_best_speed          0
avg_hyper_speed         0
whiff_percent           0
swing_percent           0
groundballs_percent     0
flyballs_percent        0
full_name               0
last_name               0
first_name              0
dtype: int64

 Checking for duplicated values:

0

In [37]:
train_df = df[df.year==2020]

,player_id,year,pa,hit,single,double,triple,home_run,k_percent,bb_percent,...,hard_hit_percent,avg_best_speed,avg_hyper_speed,whiff_percent,swing_percent,groundballs_percent,flyballs_percent,full_name,last_name,first_name
0,408234,2020,231,51,37,4,0,10,22.1,10.4,...,49.7,102.655113,96.026886,31.6,47.7,42.6,21.9,"Cabrera, Miguel",Cabrera,Miguel
1,443558,2020,214,56,34,6,0,16,27.1,11.7,...,47.2,102.723680,95.933078,34.2,47.6,47.2,21.3,"Cruz Jr., Nelson",Cruz Jr.,Nelson
2,444482,2020,218,61,45,10,1,5,20.6,6.0,...,36.3,100.556637,94.354591,21.1,46.6,51.2,18.8,"Peralta, David",Peralta,David
3,446334,2020,209,49,31,10,1,7,18.7,5.3,...,45.2,101.530260,95.520896,21.0,45.0,50.3,25.5,"Longoria, Evan",Longoria,Evan
4,452678,2020,213,46,26,9,3,8,18.8,8.9,...,38.3,97.982869,93.323023,20.5,46.1,45.5,26.6,"Cabrera, Asdrúbal",Cabrera,Asdrúbal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,669242,2020,227,51,38,7,1,5,21.1,7.0,...,33.5,98.038288,93.038932,19.0,42.7,51.3,14.6,"Edman, Tommy",Edman,Tommy
138,669256,2020,233,56,44,10,0,2,18.0,7.7,...,40.4,99.557550,94.098003,19.1,43.8,48.5,26.3,"Solak, Nick",Solak,Nick
139,669374,2020,246,46,29,4,0,13,34.6,6.5,...,39.6,99.973661,94.067657,42.7,50.1,44.0,27.6,"Hiura, Keston",Hiura,Keston
140,670032,2020,192,34,25,8,0,1,21.4,9.4,...,26.7,95.483715,91.771792,21.0,44.6,56.5,11.5,"Lopez, Nicky",Lopez,Nicky
141,673357,2020,227,47,28,8,0,11,32.2,8.8,...,40.5,101.465314,94.806749,41.5,57.6,38.2,26.7,"Robert Jr., Luis",Robert Jr.,Luis

In [38]:
df[df.year==2021]

,player_id,year,pa,hit,single,double,triple,home_run,k_percent,bb_percent,...,hard_hit_percent,avg_best_speed,avg_hyper_speed,whiff_percent,swing_percent,groundballs_percent,flyballs_percent,full_name,last_name,first_name
142,408234,2021,526,121,90,16,0,15,22.4,7.6,...,49.0,101.953387,95.613068,25.8,49.4,49.0,25.9,"Cabrera, Miguel",Cabrera,Miguel
143,443558,2021,584,136,82,21,1,32,21.6,8.7,...,52.5,105.497885,97.364589,30.7,51.0,43.4,25.5,"Cruz Jr., Nelson",Cruz Jr.,Nelson
144,444482,2021,538,126,80,30,8,8,17.1,8.6,...,41.8,101.204663,94.748490,21.3,46.5,54.9,15.6,"Peralta, David",Peralta,David
145,453568,2021,582,139,97,25,4,13,15.6,9.3,...,38.5,99.359822,93.750499,20.2,47.3,47.4,22.3,"Blackmon, Charlie",Blackmon,Charlie
146,457705,2021,574,107,55,24,1,27,23.0,14.1,...,39.5,99.449260,93.945350,25.9,41.7,40.9,30.5,"McCutchen, Andrew",McCutchen,Andrew
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,669242,2021,691,168,113,41,3,11,13.7,5.5,...,35.1,98.079996,93.108010,14.9,47.4,46.9,23.7,"Edman, Tommy",Edman,Tommy
270,669256,2021,511,111,80,18,2,11,20.9,6.7,...,33.5,98.209109,93.137324,24.8,46.0,54.6,19.7,"Solak, Nick",Solak,Nick
271,669720,2021,529,125,73,26,4,22,20.2,5.3,...,39.2,99.723845,93.967001,24.6,46.4,43.4,26.8,"Hays, Austin",Hays,Austin
272,670032,2021,565,149,120,21,6,2,13.1,8.7,...,26.9,95.857798,91.988841,15.4,45.1,58.0,16.9,"Lopez, Nicky",Lopez,Nicky
273,670541,2021,598,149,80,35,1,33,24.2,8.4,...,54.2,104.437748,97.123949,22.7,43.1,38.0,30.1,"Alvarez, Yordan",Alvarez,Yordan

In [39]:
df[df.year==2022]

,player_id,year,pa,hit,single,double,triple,home_run,k_percent,bb_percent,...,hard_hit_percent,avg_best_speed,avg_hyper_speed,whiff_percent,swing_percent,groundballs_percent,flyballs_percent,full_name,last_name,first_name
274,443558,2022,507,105,79,16,0,10,23.5,9.7,...,46.1,102.298381,95.468978,32.0,50.8,53.0,19.3,"Cruz Jr., Nelson",Cruz Jr.,Nelson
275,453568,2022,577,140,96,22,6,16,18.9,5.5,...,30.6,97.426435,92.732128,21.4,51.5,44.4,23.8,"Blackmon, Charlie",Blackmon,Charlie
276,457705,2022,580,122,80,25,0,17,21.4,9.8,...,40.0,99.926933,94.143161,24.2,44.9,41.8,28.1,"McCutchen, Andrew",McCutchen,Andrew
277,457759,2022,532,130,81,36,0,13,16.7,9.4,...,40.6,99.002546,93.736859,20.3,48.2,32.8,33.3,"Turner, Justin",Turner,Justin
278,462101,2022,577,133,84,32,0,17,15.9,6.8,...,34.8,98.336004,93.236648,21.4,45.6,46.5,22.1,"Andrus, Elvis",Andrus,Elvis
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399,673490,2022,582,130,87,29,3,11,17.2,8.8,...,32.4,97.647568,92.869313,19.1,43.3,40.8,22.9,"Kim, Ha-Seong",Kim,Ha-Seong
400,677594,2022,560,145,89,25,3,28,25.9,7.1,...,50.7,103.718796,96.379006,30.4,50.2,46.3,24.0,"Rodríguez, Julio",Rodríguez,Julio
401,677951,2022,632,150,93,31,6,20,21.4,4.7,...,38.6,100.836507,94.527116,25.2,51.8,36.2,33.4,"Witt Jr., Bobby",Witt Jr.,Bobby
402,680757,2022,638,168,130,25,7,6,9.4,9.7,...,20.8,94.219058,91.134248,9.0,38.1,42.6,23.6,"Kwan, Steven",Kwan,Steven
403,683734,2022,555,138,92,28,1,17,17.3,5.6,...,48.6,101.162950,95.128583,21.0,47.0,48.0,22.2,"Vaughn, Andrew",Vaughn,Andrew

In [40]:
df[df.year==2023]

,player_id,year,pa,hit,single,double,triple,home_run,k_percent,bb_percent,...,hard_hit_percent,avg_best_speed,avg_hyper_speed,whiff_percent,swing_percent,groundballs_percent,flyballs_percent,full_name,last_name,first_name
404,457759,2023,626,154,100,31,0,23,17.6,8.1,...,39.0,98.567368,93.587032,17.5,45.0,35.7,33.0,"Turner, Justin",Turner,Justin
405,467793,2023,619,132,75,33,1,23,16.8,10.5,...,36.4,99.367236,93.791213,22.1,45.3,43.3,24.2,"Santana, Carlos",Santana,Carlos
406,502671,2023,687,159,103,31,0,25,23.4,12.7,...,50.8,102.409596,95.767793,27.5,44.0,41.4,26.9,"Goldschmidt, Paul",Goldschmidt,Paul
407,518692,2023,730,211,121,59,2,29,16.6,9.9,...,42.2,100.590638,94.617662,20.4,51.0,35.9,29.6,"Freeman, Freddie",Freeman,Freddie
408,518934,2023,562,121,81,22,3,15,22.2,10.7,...,43.0,100.265360,94.322122,19.7,39.2,55.6,17.4,"LeMahieu, DJ",LeMahieu,DJ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,682998,2023,645,161,96,30,10,25,19.4,8.8,...,40.9,100.972563,94.780605,21.5,45.8,45.3,24.0,"Carroll, Corbin",Carroll,Corbin
534,683002,2023,622,143,77,29,9,28,25.6,9.0,...,52.0,102.730226,96.062563,26.4,46.8,45.8,26.5,"Henderson, Gunnar",Henderson,Gunnar
535,683011,2023,601,113,65,23,4,21,27.8,8.7,...,43.0,99.546177,93.954578,28.1,47.9,41.1,27.6,"Volpe, Anthony",Volpe,Anthony
536,683734,2023,615,146,93,30,2,21,21.0,5.9,...,46.5,101.661403,95.348849,24.1,47.5,44.4,23.7,"Vaughn, Andrew",Vaughn,Andrew
537,807799,2023,580,155,104,33,3,15,14.0,5.9,...,40.6,100.123813,94.280566,18.3,43.3,55.0,19.4,"Yoshida, Masataka",Yoshida,Masataka