In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('stats.csv')
df.head(n=10)
#split the last_name,first_name column to be two sepearate columns 1 for first name, 1 for last name by first creating a full_name column then splitting
df[['full_name']]= df[['last_name, first_name']]
df[['last_name','first_name']]=df.full_name.str.split(', ',expand=True)

#drop the original last_name,first_name columns 
df.drop('last_name, first_name',axis = 1,inplace=True)

print(f'There are {len(df)} observations made on {len(df.columns)} features considered in this dataset. ' +
      f' \n ' +
      f'Those features are: ' +
      f' \n')
    
for column in df.columns:
    print(column)

print(f'\n Feature of interest: on_base_plus_slg')

There are 538 observations made on 25 features considered in this dataset.
 Those features are:

player_id
year
pa
hit
single
double
triple
home_run
k_percent
bb_percent
on_base_plus_slg
exit_velocity_avg
sweet_spot_percent
barrel_batted_rate
solidcontact_percent
hard_hit_percent
avg_best_speed
avg_hyper_speed
whiff_percent
swing_percent
groundballs_percent
flyballs_percent
full_name
last_name
first_name

 Feature of interest: on_base_plus_slg

In [3]:
#make copy of original df 
df_copy = df.copy()
df_copy

,player_id,year,pa,hit,single,double,triple,home_run,k_percent,bb_percent,...,hard_hit_percent,avg_best_speed,avg_hyper_speed,whiff_percent,swing_percent,groundballs_percent,flyballs_percent,full_name,last_name,first_name
0,408234,2020,231,51,37,4,0,10,22.1,10.4,...,49.7,102.655113,96.026886,31.6,47.7,42.6,21.9,"Cabrera, Miguel",Cabrera,Miguel
1,443558,2020,214,56,34,6,0,16,27.1,11.7,...,47.2,102.723680,95.933078,34.2,47.6,47.2,21.3,"Cruz Jr., Nelson",Cruz Jr.,Nelson
2,444482,2020,218,61,45,10,1,5,20.6,6.0,...,36.3,100.556637,94.354591,21.1,46.6,51.2,18.8,"Peralta, David",Peralta,David
3,446334,2020,209,49,31,10,1,7,18.7,5.3,...,45.2,101.530260,95.520896,21.0,45.0,50.3,25.5,"Longoria, Evan",Longoria,Evan
4,452678,2020,213,46,26,9,3,8,18.8,8.9,...,38.3,97.982869,93.323023,20.5,46.1,45.5,26.6,"Cabrera, Asdrúbal",Cabrera,Asdrúbal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,682998,2023,645,161,96,30,10,25,19.4,8.8,...,40.9,100.972563,94.780605,21.5,45.8,45.3,24.0,"Carroll, Corbin",Carroll,Corbin
534,683002,2023,622,143,77,29,9,28,25.6,9.0,...,52.0,102.730226,96.062563,26.4,46.8,45.8,26.5,"Henderson, Gunnar",Henderson,Gunnar
535,683011,2023,601,113,65,23,4,21,27.8,8.7,...,43.0,99.546177,93.954578,28.1,47.9,41.1,27.6,"Volpe, Anthony",Volpe,Anthony
536,683734,2023,615,146,93,30,2,21,21.0,5.9,...,46.5,101.661403,95.348849,24.1,47.5,44.4,23.7,"Vaughn, Andrew",Vaughn,Andrew
537,807799,2023,580,155,104,33,3,15,14.0,5.9,...,40.6,100.123813,94.280566,18.3,43.3,55.0,19.4,"Yoshida, Masataka",Yoshida,Masataka

In [4]:
df.drop('full_name',axis=1,inplace=True)

In [5]:
df.drop('last_name',axis=1,inplace=True)

In [6]:
df.drop('first_name',axis=1,inplace=True)

In [7]:
print(f'\n Checking for missing (Na) values: \n ')
print(f'{df.isna().sum()}')
print(f'\n Checking for duplicated values: \n ')
print(f'{df.duplicated().sum()}')

 Checking for missing (Na) values:

player_id               0
year                    0
pa                      0
hit                     0
single                  0
double                  0
triple                  0
home_run                0
k_percent               0
bb_percent              0
on_base_plus_slg        0
exit_velocity_avg       0
sweet_spot_percent      0
barrel_batted_rate      0
solidcontact_percent    0
hard_hit_percent        0
avg_best_speed          0
avg_hyper_speed         0
whiff_percent           0
swing_percent           0
groundballs_percent     0
flyballs_percent        0
dtype: int64

 Checking for duplicated values:

0

In [ ]:
train_df = df[(df['year'] == 2021) | (df['year'] == 2020)]
train_df.head(n=5)
len(train_df.columns)

In [ ]:
val_df = df[df.year==2022]
len(val_df.columns)
val_df.head(n=5)

In [ ]:
test_df = df[df.year==2023]
len(test_df.columns)
test_df.head(n=5)

In [ ]:
# a = df
#a.drop('last_name',axis=1,inplace=True)
#a.drop('full_name',axis=1,inplace=True)
#a.drop('first_name',axis=1,inplace=True)
# a.corr()

In [ ]:
correlation_matrix = df.corr()

# Define threshold
threshold = 0.6  # Adjust the threshold as needed

# Filter correlation matrix to find highly correlated pairs
highly_correlated_pairs = []
for i in range(len(correlation_matrix.columns)):
    for j in range(i+1, len(correlation_matrix.columns)):
        if abs(correlation_matrix.iloc[i, j]) > threshold:
            highly_correlated_pairs.append((correlation_matrix.columns[i], correlation_matrix.columns[j], correlation_matrix.iloc[i, j]))

# Display highly correlated pairs
print("Pairs of variables with correlation greater than", threshold, ":")
for pair in highly_correlated_pairs:
    print(pair)